service: form-receiver-poc
frameworkVersion: '2'
configValidationMode: error

custom:
  topicName: form-receiver-topic
  queueName: form-receiver-queue

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  region: ${opt:region, 'us-east-1'}
  
  environment:
    SNS_TOPIC_NAME: ${self:custom.topicName}
    SNS_TOPIC_ARN: !Ref FormTopic

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: '*'
          Resource: arn:aws:sns:*:*:${self:custom.topicName}
        - Effect: 'Allow'
          Action:
            - '*'
          Resource: arn:aws:sqs:*:*:${self:custom.queueName}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  submit: # Lambda validates form submission & publishes message to SNS topic
    handler: bin/submit
    events:
      - httpApi:
          path: /submit
          method: post

  process:
    handler: bin/process
    events:
      - sqs:
          arn: !GetAtt
            - FormQueue
            - Arn



resources:
  Resources:

    FormTopic: # Create SNS Topic
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}

    FormQueue: # Create SQS Queue
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}

    FormQueueTopicSubscription:
      Type: AWS::SNS::Subscription # subscribe SQS to SNS topic
      Properties:
        TopicArn: !Ref FormTopic
        Endpoint: !GetAtt
          - FormQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'true'

    AuditQueueSNSPolicy:
      Type: AWS::SQS::QueuePolicy # allow SNS to send messages to SQS
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Action: SQS:SendMessage
              Resource: !GetAtt
                - FormQueue
                - Arn
              Condition:
                ArnEquals:
                  'aws:SourceArn': !Ref FormTopic
        Queues:
          - Ref: FormQueue
